import {useCallback,useEffect,useMemo,useState} from 'react';
import type {Command,Coord,Die,Side} from '../game/types';
import {createGame} from '../game/engine';
import {RESOURCES,template} from '../game/content';
import {equal,findPlacement,index,legalPlacement,placementCells} from '../game/board';
import {reachable} from '../game/movement';
import Board from './Board';
import DiceTray from './DiceTray';
import {Icon,Modal,Net,QR,Rules,title} from './components';
import {useRoom} from './useRoom';

type Mode='inspect'|'compile'|'move'|'attack'|'flip'|'utility';
export default function App(){
 const game=useRoom(),{room,busy,error,online,local}=game;
 const [modal,setModal]=useState<'create'|'rules'|'invite'|'resign'|null>(null),[role,setRole]=useState<Side>('runner');
 const [name,setName]=useState(()=>localStorage.getItem('cdd:name')??''),[copied,setCopied]=useState(false),[inspected,setInspected]=useState<Die|null>(null);
 const [selectedDice,setSelectedDice]=useState<string[]>([]),[selectedUnit,setSelectedUnit]=useState('avatar');
 const [mode,setMode]=useState<Mode>('inspect'),[compileDie,setCompileDie]=useState<string|null>(null),[rotation,setRotation]=useState(0),[anchor,setAnchor]=useState<Coord|null>(null),[hover,setHover]=useState<Coord|null>(null),[discard,setDiscard]=useState('');
 const [reviewingWinner,setReviewingWinner]=useState(false),[placementError,setPlacementError]=useState('');
 const [topDown,setTopDown]=useState(false),[zoom,setZoom]=useState(1),[guard,setGuard]=useState(0);
 const s=room?.state,side=room?.side??role,previewState=useMemo(()=>createGame('presentation'),[]);
 const state=s??previewState;
 const myTurn=!!room&&room.ready&&state.activeSide===side&&!state.pending&&!state.winner;
 const canAct=myTurn&&state.stage==='actions'&&!busy&&online;
 const unit=state.units.find(u=>u.id===selectedUnit&&u.side===side)??state.units.find(u=>u.side===side);
 const die=state.loadouts[side].find(d=>d.id===compileDie);
 const origin=anchor??hover,compileValid=!!(die&&origin&&legalPlacement(state,side,die.netId,origin,rotation));
 const invite=room&&!local?`${location.origin}/?room=${room.id}`:'';
 const defense=state.pending?.defender===side&&!!room;
 const maxGuard=state.pending?Math.min(state.resources[side].guard,state.pending.damage):0;
 const dataCount=state.data.filter(d=>d.breached).length,avatar=state.units.find(u=>u.id==='avatar');
 const hoverUnit=hover?state.units.find(u=>equal(u,hover)):null;

 useEffect(()=>{if(!room)return;setSelectedDice(state.loadouts[side].filter(d=>!d.compiled).slice(0,3).map(d=>d.id));setSelectedUnit(state.units.find(u=>u.side===side)?.id??'');setMode('inspect');setCompileDie(null);setAnchor(null);},[state.round,state.activeSide,room?.side]);
 useEffect(()=>{if(!state.winner)setReviewingWinner(false);},[state.winner]);
 useEffect(()=>{setGuard(maxGuard);},[state.pending?.target,state.pending?.attacker]);
 useEffect(()=>{if(!canAct&&mode!=='inspect'){setMode('inspect');setCompileDie(null);setAnchor(null);}},[state.activeSide,state.stage,state.pending,state.winner]);
 const onHover=useCallback((p:Coord|null)=>setHover(old=>old&&p&&equal(old,p)?old:p),[]);
 const highlights=useMemo(()=>mode==='move'&&unit&&canAct?[...reachable(state,unit).keys()].filter(i=>i!==index(unit)).map(i=>({x:i%15,y:Math.floor(i/15)})):[],[state,unit,mode,canAct]);
 const view=useMemo(()=>({highlights,preview:mode==='compile'&&die&&origin?placementCells(die.netId,origin,rotation):[],valid:compileValid,selected:room?unit?.id??null:null,hover,topDown,zoom}),[highlights,mode,die,origin,rotation,compileValid,unit,hover,topDown,zoom,room]);
 async function act(c:Command,after:Mode='inspect'){if(await game.execute(c)){setMode(after);if(c.type==='compile'){setCompileDie(null);setAnchor(null);}}}
 function pick(p:Coord){if(!room)return;const target=state.units.find(u=>equal(u,p));
  if(mode==='compile'&&canAct){setAnchor(p);return;}
  if(mode==='move'&&canAct&&unit){if(target?.side===side)setSelectedUnit(target.id);else void act({type:'move',unitId:unit.id,to:p},'move');return;}
  if(mode==='attack'&&canAct&&unit){if(target?.side===side)setSelectedUnit(target.id);else if(target)void act({type:'attack',unitId:unit.id,targetId:target.id});return;}
  if(mode==='flip'&&canAct){void act({type:'flip',to:p},'flip');return;}
  if(mode==='utility'&&canAct&&unit){void act({type:'ability',unitId:unit.id,to:p},'utility');return;}
  if(target?.side===side)setSelectedUnit(target.id);
 }
 function startCompile(id:string){setPlacementError('');setCompileDie(id);setRotation(0);setAnchor(null);setMode('compile');setDiscard(state.daemons[0]?.id??'');}
 function suggestPlacement(){if(!die)return;const p=findPlacement(state,side,die.netId);if(p){setRotation(p.rotation);setAnchor(p.origin);setPlacementError('');}else{setAnchor(null);setPlacementError('No legal placement remains for this die. Choose another Deploy die or take an action.');}}
 async function copyInvite(){try{await navigator.clipboard.writeText(invite);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{const input=document.querySelector<HTMLInputElement>('.invite-link');input?.focus();input?.select();}}
 async function downloadReplay(){let data:unknown;if(local)data={format:'cyber-dice-duel-replay-v1',seed:state.seed,events:state.eventLog,metrics:state.metrics,winner:state.winner};else {const r=await fetch(`/api/rooms/${room!.id}/replay`);if(!r.ok)return;data=await r.json();}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cyber-dice-duel-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
 const instructions=mode==='compile'?'Choose an origin cell, then confirm the unfolded path.':mode==='move'?'Select a highlighted destination. Your unit takes the cheapest legal route.':mode==='attack'?'Select an adjacent enemy. The defender will choose their Guard.':mode==='flip'?'Select your cell or an adjacent secured cell to corrupt.':mode==='utility'?'Select a legal target within one cell of your Utility ICE.':'Select a unit to inspect it. Build your route toward the Data.';
 const canBreach=canAct&&side==='runner'&&!!avatar&&state.data.some(d=>!d.breached&&equal(d,avatar))&&state.resources.runner.ability>=2;

 return <div className={`app ${room?'in-game':'landing'} theme-${side}`}>
  <header className="site-header"><a className="brand" href="/" aria-label="Cyber Dice Duel home"><Icon name="deploy" size={34}/><span>CYBER<span className="brand-light">DICE DUEL</span></span><span className="build-tag">PROTOTYPE / 01</span></a><nav>{room&&<span className={`connection ${online?'':'offline'}`}>{local?'LOCAL DUEL':online?'CONNECTED':'RECONNECTING'}</span>}<button className="quiet" onClick={()=>setModal('rules')}>How to play <span className="keycap">?</span></button>{room&&!local&&<button className="outline small" onClick={()=>setModal('invite')}>Invite link ↗</button>}</nav></header>
  {error&&<div className="error-bar" role="alert"><span>{error}</span><button className="quiet small" onClick={()=>void game.refresh()}>Refresh</button><button className="quiet small" aria-label="Dismiss message" onClick={game.clearError}>×</button></div>}
  {!room?<>
   <main className="hero"><section className="hero-copy"><div className="eyebrow"><span className="live-square"/> ASYMMETRIC TACTICAL DUEL · 2 PLAYERS</div><h1>BUILD.<br/><span>BREACH.</span><br/>ESCAPE.</h1><p className="hero-description">Every die is a way in.<br/>Unfold your network. Outthink your opponent.<br/>Steal the data before the window closes.</p>
    {game.loading?<div className="joining"><span className="spinner"/> Opening your duel…</div>:game.joinInfo?<div className="join-card"><span className="eyebrow">INCOMING CONNECTION</span><h2>{game.joinInfo.ready?'This duel has two players':`${game.joinInfo.hostName} is waiting`}</h2><p>{game.joinInfo.ready?'Return using the browser you originally joined with.':`Take the ${title(game.joinInfo.openSide)} seat and enter the network.`}</p>{!game.joinInfo.ready&&<form onSubmit={e=>{e.preventDefault();void game.enter('join',name);}}><label htmlFor="join-name">Your callsign</label><input id="join-name" value={name} onChange={e=>setName(e.target.value)} maxLength={24} placeholder="Enter a callsign" required autoComplete="nickname"/><button className="primary" disabled={busy}>{busy?'Connecting…':`Join as ${title(game.joinInfo.openSide)} →`}</button></form>}<a className="text-link" href="/">Start a different duel</a></div>:<div className="hero-actions"><button className="primary large" onClick={()=>setModal('create')}>Create a duel <span>↗</span></button><button className="text-link" onClick={game.practice}>Try a local duel <span>→</span></button></div>}
    <div className="hero-facts"><div><b>15 × 11</b><span>EXPANDING GRID</span></div><div><b>11</b><span>CUBE NETS</span></div><div><b>2</b><span>OPPOSING ROLES</span></div></div>
   </section><section className="hero-board"><div className="board-caption"><span>THE NETWORK</span><span>RECON / AWAITING INTRUSION</span></div><Board state={previewState} view={{...view,selected:null}} onPick={()=>{}} onHover={onHover}/><div className="hero-board-legend"><span><i className="runner-dot"/> RUNNER GATEWAY</span><span className="muted">CONNECT. CONTEST. EXTRACT.</span><span><i className="corp-dot"/> CORP CORE</span></div><div className="hero-net-note"><Net id="NET-08"/><span><b>A die becomes your next six steps.</b><small>Six faces. One connected path. Your move.</small></span></div></section></main>
   <footer className="landing-footer"><span>NO ACCOUNT NEEDED. JUST AN OPPONENT.</span><span>SHARE A LINK · SCAN A QR · ENTER THE DUEL</span></footer>
  </>:<main className="game-main">
   <div className="duel-header"><div className="player-label runner-text"><span className="role-number">01</span><div><span className="eyebrow">RUNNER {side==='runner'?' / YOU':''}</span><strong>{room.players.runner??'Waiting for Runner'}</strong></div></div><div className="round-label"><span className="eyebrow">{state.phase==='recon'?'RECON PHASE':'INTRUSION ACTIVE'}</span><strong>ROUND {String(state.round).padStart(2,'0')}</strong><span className="clock">{state.phase==='recon'?'CLOCK PAUSED':`${state.timer} ROUNDS REMAINING`}</span></div><div className="player-label corp-text"><div><span className="eyebrow">CORP {side==='corp'?' / YOU':''}</span><strong>{room.players.corp??'Waiting for Corp'}</strong></div><span className="role-number">02</span></div></div>
   <div className="mobile-objectives"><span>AVATAR <b>{avatar?.hp??0}/8</b></span><span>DATA <b>{dataCount}/2</b></span><span>DAEMONS <b>{state.daemons.length}/3</b></span></div>
   <div className="battle-layout">
    <aside className="left-panel"><div className="section-title">{title(side)} resources <small>MAX 9</small></div><div className="resource-grid">{RESOURCES.map(resource=><div className="resource" key={resource}><Icon name={resource} size={27}/><span>{title(resource)}</span><b>{state.resources[side][resource]}</b></div>)}</div>
     <div className="section-title">The objective</div><div className="objective-status"><span className="muted">AVATAR INTEGRITY</span><strong>{avatar?.hp??0}<small> / 8</small></strong><div className="integrity-bar">{Array.from({length:8},(_,i)=><i key={i} className={i<(avatar?.hp??0)?'filled':''}/>)}</div><div className="data-count"><span>DATA ACQUIRED</span><b>{dataCount} <small>/ 2</small></b></div><div className="data-nodes">{state.data.map(d=><span key={d.id} className={d.breached?'stolen':''}>◈ {d.id} {d.breached?'✓':''}</span>)}</div></div>
     <div className="mission-note">{side==='runner'?dataCount>=2?'You have the Data. Return to the Gateway to extract.':'Breach two Data Nodes, then return to your Gateway.':'Crash the Avatar or hold it inside the network until time runs out.'}</div>
     <div className="section-title">{side==='runner'?'Installed daemons':'Your ICE'}<small>{side==='runner'?`${state.daemons.length}/3`:state.units.filter(u=>u.side==='corp').length}</small></div>
     {side==='runner'?<div className="daemon-list">{state.daemons.length?state.daemons.map(d=><div key={d.id}><b>{template(d.template).name}</b><small>{template(d.template).description}</small></div>):<p className="empty-note">Compile a Ghost or Daemon die to install an upgrade.</p>}</div>:<div className="unit-list">{state.units.filter(u=>u.side==='corp').map(u=><button key={u.id} className={unit?.id===u.id?'active':''} onClick={()=>{setSelectedUnit(u.id);setMode('inspect');}}><span>{u.name}</span><small>{u.hp}/{u.maxHp} HP</small></button>)}</div>}
    </aside>
    <section className="board-column"><div className="board-toolbar"><span className="eyebrow">NETWORK / 15 × 11</span><div><button className="small quiet" aria-pressed={topDown} onClick={()=>setTopDown(v=>!v)}>{topDown?'Angled view':'Top view'}</button><button className="icon-button" aria-label="Zoom out" disabled={zoom<=.8} onClick={()=>setZoom(v=>Math.max(.8,v-.1))}>−</button><button className="icon-button" aria-label="Zoom in" disabled={zoom>=1.6} onClick={()=>setZoom(v=>Math.min(1.6,v+.1))}>+</button></div></div>
     <div className="battle-board"><Board state={state} view={view} onPick={pick} onHover={onHover}/>{!room.ready&&<div className="waiting-overlay"><div><span className="pulse-ring"/><span className="eyebrow">ROOM CREATED</span><h2>Waiting for your opponent.</h2><p>One link is all it takes to connect.</p><QR url={invite}/><button className="primary" onClick={copyInvite}>{copied?'Link copied ✓':'Copy invite link ↗'}</button><small>Scan with a second device to join.</small></div></div>}</div>
     <div className="board-footer"><span><i className="runner-dot"/> BACKDOOR</span><span><i className="corp-dot"/> SECURED</span><span><i className="data-dot"/> DATA</span><span className="hover-info">{hoverUnit?`${hoverUnit.name} · ${hoverUnit.hp}/${hoverUnit.maxHp} HP`:hover?`CELL ${hover.x+1}, ${hover.y+1}`:'SELECT A CELL'}</span></div>
     <div className="instruction-bar" aria-live="polite"><span className="instruction-mark">{mode==='compile'?'◇':mode==='move'?'↗':'⌖'}</span><span>{room.ready?instructions:'Share the QR or invite link to begin.'}</span>{mode!=='inspect'&&<button className="quiet small" onClick={()=>{setMode('inspect');setCompileDie(null);setAnchor(null);}}>Cancel</button>}</div>
    </section>
    <aside className="action-panel">
     <div className={`turn-status ${defense?'defending':myTurn?'your-turn':''}`}><span className="eyebrow">{local?'LOCAL / PASS THE SCREEN':`YOU ARE THE ${side.toUpperCase()}`}</span><h2>{state.winner?'DUEL COMPLETE':!room.ready?'STANDING BY':defense?'DEFEND NOW':state.pending?'AWAITING GUARD':myTurn?'YOUR TURN':'OPPONENT TURN'}</h2><p>{state.winner?state.winReason:!room.ready?'Connect an opponent to start.':defense?'Your opponent has committed an attack.':state.pending?'The defender is choosing a response.':myTurn?state.stage==='choose'?'Select dice from your loadout below.':state.stage==='rolled'?'Spend Code to reroll, or lock your results.':'Spend your resources. Shape the network.':`${title(state.activeSide)} is making their move.`}</p></div>
     {state.winner&&<button className="primary full" onClick={()=>setReviewingWinner(false)}>View duel result →</button>}
     {defense?<div className="defense-controls"><div className="incoming"><strong>{state.pending!.damage}</strong><span>INCOMING DAMAGE</span></div><label htmlFor="guard">Spend Guard <b>{guard}</b></label><input id="guard" type="range" min="0" max={maxGuard} value={guard} onChange={e=>setGuard(Number(e.target.value))}/><p className="muted">{guard} Guard prevents {guard} damage.</p><button className="primary" disabled={busy||!online} onClick={()=>void act({type:'defend',guard})}>{busy?'Resolving…':guard?`Block ${guard} damage`:'Take the hit'}</button></div>:<>
      {myTurn&&state.stage==='choose'&&<button className="primary roll-button" disabled={busy||!online||selectedDice.length!==Math.min(3,state.loadouts[side].filter(d=>!d.compiled).length)} onClick={()=>void act({type:'roll',dice:selectedDice})}><Icon name="deploy" size={28}/>{busy?'Rolling…':`Roll ${selectedDice.length} dice`}</button>}
      {myTurn&&state.stage==='rolled'&&<><div className="result-summary">{state.rolled.map(r=><span key={r.id}><Icon name={r.face} size={37}/><small>{title(r.face)}</small></span>)}</div><button className="primary" disabled={busy||!online} onClick={()=>void act({type:'lock'})}>Lock results →</button><p className="empty-note">{state.rerolled?'Reroll used.':state.resources[side].code?'Use ↻ on a rolled die below for 1 Code.':'No saved Code available for a reroll.'}</p></>}
      {myTurn&&state.stage==='actions'&&<>
       {mode==='compile'&&die?<div className="placement-controls"><div className="placement-title"><Net id={die.netId} rotation={rotation}/><div><strong>{template(die.template).name}</strong><small>{die.netId} · {rotation*90}°</small></div></div><p>Tap a cell to pin the origin.</p>{placementError&&<p className="invalid" role="status">{placementError}</p>}<div className="button-row"><button className="outline small" onClick={()=>setRotation(r=>(r+1)%4)}>Rotate ↻</button><button className="outline small" onClick={suggestPlacement}>Find space</button></div>{anchor&&<div className={`placement-verdict ${compileValid?'valid':'invalid'}`}>{compileValid?'✓ Six cells fit here':'× Overlap, edge, or no connection'}</div>}{state.daemons.length===3&&['ghost','daemon'].includes(die.template)&&<label>Replace Daemon<select value={discard} onChange={e=>setDiscard(e.target.value)}>{state.daemons.map(d=><option key={d.id} value={d.id}>{template(d.template).name}</option>)}</select></label>}<button className="primary" disabled={!anchor||!compileValid||busy} onClick={()=>{if(anchor)void act({type:'compile',dieId:die.id,origin:anchor,rotation,discardDaemon:discard});}}>Unfold here →</button></div>:<>
        {state.compilationOpen&&state.rolled.filter(r=>r.face==='deploy').length>=2&&<div className="compile-callout"><Icon name="deploy" size={28}/><div><b>Compilation available</b><p>Choose “Unfold” on a Deploy die below, before another action.</p></div></div>}
        <div className="movement-budget"><span>{side==='runner'?'MOBILITY':'COMMAND'} POINTS</span><strong>{state.movement.points}</strong></div>
        <button className="outline full" disabled={!canAct||state.resources[side].move<1} onClick={()=>void act({type:'chargeMove'},'move')}><Icon name="move"/>Spend Move <small>+{side==='runner'?4+state.daemons.filter(d=>d.template==='daemon').length:2} points</small></button>
        {unit&&<div className="selected-unit"><div className="section-title">Selected unit</div><h3>{unit.name}</h3>{side==='corp'&&<select aria-label="Select your ICE" className="ice-picker" value={unit.id} onChange={e=>setSelectedUnit(e.target.value)}>{state.units.filter(u=>u.side===side).map(u=><option value={u.id} key={u.id}>{u.name} · {u.hp}/{u.maxHp} HP</option>)}</select>}<div className="unit-stats"><span><b>{unit.hp}</b>/{unit.maxHp} HP</span><span><b>{unit.power}</b> POWER</span>{unit.shield>0&&<span><b>{unit.shield}</b> SHIELD</span>}</div><div className="action-grid"><button className={mode==='move'?'active':''} disabled={!canAct||state.movement.points===0||unit.moveCap===0} onClick={()=>setMode('move')}><Icon name="move"/>Move</button><button className={mode==='attack'?'active':''} disabled={!canAct||state.resources[side].attack<1||state.attacked.includes(unit.id)} onClick={()=>setMode('attack')}><Icon name="attack"/>Attack</button>{side==='runner'?<button className={mode==='flip'?'active':''} disabled={!canAct||state.resources[side].ability<1} onClick={()=>setMode('flip')}><Icon name="ability"/>Corrupt</button>:['repair','reinforce','sanitise'].includes(unit.kind)?<button className={mode==='utility'?'active':''} disabled={!canAct||state.resources[side].ability<1} onClick={()=>setMode('utility')}><Icon name="ability"/>Utility</button>:null}{side==='runner'&&<button disabled={!canBreach} onClick={()=>void act({type:'breach'})}><Icon name="ability"/>Breach <small>2</small></button>}</div></div>}
       </>}
       <button className="end-turn" disabled={busy||!online} onClick={()=>void act({type:'end'})}>End turn <span>→</span></button>
      </>}
     </>}
     <details className="event-log" open><summary>ACTIVITY <span>{state.eventLog.length?'●':'—'}</span></summary><div>{state.eventLog.slice(-6).reverse().map(e=><p key={e.index}><span className={e.side+'-text'}>{String(e.index+1).padStart(2,'0')}</span>{e.text}</p>)}{!state.eventLog.length&&<p>The network is quiet. Your first move starts here.</p>}</div></details>
     {room.ready&&!state.winner&&<button className="concede quiet small" onClick={()=>setModal('resign')}>Concede duel</button>}
    </aside>
   </div>
   <DiceTray state={state} side={side} selected={selectedDice} onSelect={id=>setSelectedDice(old=>old.includes(id)?old.filter(x=>x!==id):old.length<Math.min(3,state.loadouts[side].filter(d=>!d.compiled).length)?[...old,id]:old)} onReroll={dieId=>void act({type:'reroll',dieId})} onCompile={startCompile} active={myTurn} busy={busy} compileDie={compileDie} onInspect={setInspected}/>
  </main>}
  {state.winner&&room&&!reviewingWinner&&<Modal title={state.winner==='runner'?'DATA EXTRACTED':'NETWORK SECURED'} onClose={()=>setReviewingWinner(true)}><div className={`winner-card ${state.winner}-text`}><Icon name={state.winner==='runner'?'ability':'guard'} size={84}/><span className="eyebrow">{room.players[state.winner]} WINS</span><h2>{state.winReason}</h2><p>{state.round} rounds · {state.metrics.compilations} paths compiled · {state.metrics.breached} Data breached</p><button className="primary" onClick={()=>{if(local)game.practice();else location.assign('/');}}>Play another duel →</button><button className="outline" onClick={()=>void downloadReplay()}>Download match replay</button></div></Modal>}
  {modal==='rules'&&<Modal title="The field guide" onClose={()=>setModal(null)}><Rules/></Modal>}
  {modal==='create'&&<Modal title="Choose your side." onClose={()=>setModal(null)}><p className="muted">Same dice. Different ambitions.</p><form onSubmit={async e=>{e.preventDefault();await game.enter('create',name,role);setModal(null);}}><div className="role-select" role="radiogroup" aria-label="Your role"><button type="button" role="radio" aria-checked={role==='runner'} className={`runner-choice ${role==='runner'?'chosen':''}`} onClick={()=>setRole('runner')}><span>01 / RUNNER</span><Icon name="ability" size={50}/><strong>Breach & escape.</strong><small>One agile Avatar. Steal two Data and make it home.</small></button><button type="button" role="radio" aria-checked={role==='corp'} className={`corp-choice ${role==='corp'?'chosen':''}`} onClick={()=>setRole('corp')}><span>02 / CORP</span><Icon name="guard" size={50}/><strong>Contain & crash.</strong><small>A network of ICE. Stop the Runner before extraction.</small></button></div><label htmlFor="callsign">Your callsign</label><input id="callsign" value={name} onChange={e=>setName(e.target.value)} maxLength={24} placeholder="Enter a callsign" required autoComplete="nickname"/><button className="primary full" disabled={busy}>{busy?'Creating room…':'Create room & get invite →'}</button><p className="form-note">Your opponent joins by link or QR. No account required.</p></form></Modal>}
  {modal==='invite'&&<Modal title="Bring your opponent." onClose={()=>setModal(null)}><div className="invite-content"><QR url={invite}/><p>Scan with a second device, or send the link.</p><input className="invite-link" aria-label="Invite link" value={invite} readOnly onFocus={e=>e.target.select()}/><button className="primary full" onClick={copyInvite}>{copied?'Copied to clipboard ✓':'Copy invite link ↗'}</button><small>Reopen this link in the same browser to resume your seat.</small></div></Modal>}
  {modal==='resign'&&<Modal title="Concede this duel?" onClose={()=>setModal(null)}><p>{title(side==='runner'?'corp':'runner')} will win immediately. You can also close the tab and resume later.</p><div className="button-row"><button className="outline" onClick={()=>setModal(null)}>Keep playing</button><button className="danger" disabled={busy} onClick={async()=>{await act({type:'resign'});setModal(null);}}>Concede duel</button></div></Modal>}
  {inspected&&<Modal title={template(inspected.template).name} onClose={()=>setInspected(null)}><div className="die-detail"><Net id={inspected.netId}/><span className="eyebrow">{template(inspected.template).category} / {inspected.netId}</span><p>{template(inspected.template).description}</p><div className="detail-faces">{inspected.faces.map((f,i)=><div key={i}><Icon name={f} size={38}/><span>{title(f)}</span></div>)}</div><p className="muted">Compile this die to unfold its six-face path. The marked square is the origin.</p></div></Modal>}
 </div>;
}
