import {useEffect,useRef} from 'react';
import type {ReactNode} from 'react';
import QRCode from 'qrcode';
import type {Symbol} from '../game/types';
import {NETS,rotatedNet} from '../game/cube-nets';
export const title=(s:string)=>s.charAt(0).toUpperCase()+s.slice(1);
export function Icon({name,size=22}:{name:Symbol;size?:number}){return <img className="symbol" src={`/symbols/${name}.svg`} width={size} height={size} alt={title(name)} draggable={false}/>;}
export function Net({id,rotation=0}:{id:string;rotation?:number}){const cells=rotatedNet(id,rotation),minX=Math.min(...cells.map(c=>c.x)),minY=Math.min(...cells.map(c=>c.y)),maxX=Math.max(...cells.map(c=>c.x)),maxY=Math.max(...cells.map(c=>c.y));return <svg className="net" viewBox={`-2 -2 ${(maxX-minX+1)*12+4} ${(maxY-minY+1)*12+4}`} aria-label={`${id} unfolding pattern`} role="img">{cells.map((c,i)=><g key={i}><rect x={(c.x-minX)*12} y={(c.y-minY)*12} width="10" height="10" rx="1" fill={c.x===0&&c.y===0?'currentColor':'none'} stroke="currentColor" strokeWidth=".8"/>{c.x===0&&c.y===0&&<circle cx={(c.x-minX)*12+5} cy={(c.y-minY)*12+5} r="1.3" fill="#0c1117"/>}</g>)}</svg>;}
export function Modal({title:heading,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} className="modal" aria-label={heading} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-inner"><div className="modal-heading"><h2>{heading}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}>×</button></div>{children}</div></dialog>;}
export function QR({url}:{url:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(ref.current)QRCode.toCanvas(ref.current,url,{width:232,margin:3,errorCorrectionLevel:'M',color:{dark:'#101720',light:'#ffffff'}}).catch(()=>{});},[url]);return <canvas className="qr" ref={ref} aria-label="QR code containing the invite link" role="img"/>;}
export function Rules(){return <div className="rules-content">
 <p className="intro">One intruder. One network. Two ways to take control.</p>
 <div className="rule-columns"><section><h3 className="runner-text">Runner · breach & escape</h3><p>Guide your Avatar to any two blue Data Nodes. Spend 2 Ability on each to steal its Data, then return to the Gateway on the left. Your Avatar has 8 Integrity and 2 Power.</p></section><section><h3 className="corp-text">Corp · contain & crash</h3><p>Expand secured routes and deploy ICE. Crash the Avatar or keep it trapped until the Intrusion Window closes. Coordinate multiple ICE with shared Command Points.</p></section></div>
 <h3>Your turn</h3><ol><li><b>Choose three dice.</b> Every die has six faces and its own fixed cube net. Compiled dice permanently leave your loadout. If fewer than three remain, roll them all.</li><li><b>Roll, then lock.</b> Spend one Code saved before this roll to reroll one die, once. Locking banks all non-Deploy symbols (maximum 9 of each).</li><li><b>Unfold a path.</b> With two Deploy results, compile one die showing Deploy. Rotate its net, choose six empty cells touching your territory, then confirm. You must compile before taking another action.</li><li><b>Move and act.</b> Spend resources in any order, then end your turn. The Runner always acts first in a round.</li></ol>
 <div className="symbol-guide">{(['deploy','move','attack','guard','code','ability'] as Symbol[]).map((s,i)=><div key={s}><Icon name={s} size={30}/><span><b>{title(s)}</b><small>{['Two results let one die unfold. Not stored.','Runner: 4 mobility. Corp: 2 command.','One adjacent attack per unit per turn.','Defender chooses how many to spend. Each blocks 1 damage.','One saved Code buys one reroll.','Breach, corrupt, or activate a Utility ICE.'][i]}</small></span></div>)}</div>
 <h3>Movement & territory</h3><p>Orthogonal movement only. Your cells cost 1 point to enter; opposing cells cost 2. Empty cells and occupied cells cannot be crossed. Each ICE moves at most two cells per turn (Sentry: one, Firewall: zero). Movement expires at turn end. Click a reachable destination to take the cheapest legal route.</p><p>The Runner can corrupt its cell or an adjacent secured cell for 1 Ability, unless enemy ICE occupies it. The Gateway and Core cannot change ownership. Utility ICE can repair, reinforce or sanitise within one cell; see each die’s effect.</p>
 <h3>The Intrusion Window</h3><p>The clock is paused during Recon. Entering or corrupting secured territory, attacking ICE or breaching Data starts a 12-round window. The triggering round is free; later complete rounds cost one. Each newly stolen Data restores two rounds, capped at 12.</p>
 <h3>Programs & combat</h3><p>Compiled Runner dice grant an immediate Exploit, a persistent Daemon, or a one-use Payload at the net’s marked origin. Three Daemon slots are available. A fourth replaces a chosen Daemon. Mine payloads deal 2 damage to the next ICE entering; restore payloads heal the Avatar by 2.</p><p>An attack pauses play for the defender’s Guard choice, even with no Guard. Shields absorb remaining damage automatically. ICE at zero Integrity is deleted; its path remains.</p>
 <h3>The eleven cube nets</h3><div className="net-gallery">{NETS.map(n=><div key={n.id}><Net id={n.id}/><small>{n.id}</small></div>)}</div><p className="muted">Highlighted square = deployment origin. Quarter turns are allowed; mirroring is not.</p>
 <h3>Playing online</h3><p>Create a room, share its invite link or QR code, and let your opponent claim the other role. Keep the link to resume in the same browser. Two browser profiles or separate devices are needed for two seats. Turns and reactions wait for players; closing a tab does not concede. Replays can be downloaded after the duel.</p>
 </div>;}
